Feature/#2 profile view
Team-EverFlow/CheckAndTalk_FrontEnd pull request #4
Opened 2023-05-29 07:44 UTC by Mule129

## 관련 이슈
- closes #2 프로필 영역 디자인 추가

## 구현/변경 사항
프로필 디자인 컴포넌트 추가
App.js, App.css 변경하여 컴포넌트 적용 디자인 확인 가능

## 스크린샷
![image](https://github.com/Team-EverFlow/CheckAndTalk_FrontEnd/assets/51021398/70d4dd00-97d4-45be-9057-5bbe3a3a2d16)

2023-05-29 08:11 UTC, HanGyeongjun approved these changes
LGTM 수고하셨습니다!
전체적으로 html 구조 깔끔하게 잘 짜신 것 같아요
아래 리뷰 남긴 내용만 한 번 확인해주세요 👍🏻

2023-05-29 08:11 UTC, HanGyeongjun commented on check-and-talk/src/App.js
> +        </header> */}
사용하지 않는 주석은 지워주세요!

2023-05-29 08:11 UTC, HanGyeongjun commented on check-and-talk/src/components/ProfileEdit.css
> +}
확인 버튼 조금 두꺼운 폰트 적용해 주실 수 있을까요?

2023-05-29 08:11 UTC, HanGyeongjun commented on check-and-talk/src/components/ProfileEdit.css
> +    border-width: 5px;
```suggestion
    border-width: 2px;
```

border 두께가 조금 두꺼워서 웹상에서 부담스럽게 느껴질 수 있을 것 같아요

2023-05-29 08:29 UTC, 2jihye10 requested changes
수고하셨습니다 bb

- 프로필 카드에 닉네임과 상태메시지 부분의 수정 아이콘을 없애고 클릭시 수정이 가능하도록 구현하는건 어떨까요?
- 프로필 수정 부분에서 확인을 오른쪽으로 옮기는 것이 더 좋을 것 같습니다! 
- 닉네임 길이에 따른 위치 고정도 필요할 것 같습니다.
    - 닉네임의 시작 위치를 고정하여 닉네임이 길수록 오른쪽으로 길어지는 방식
    - 닉네임의 길이를 파악하여 길이에 따라 중앙 정렬  
- Lv.1 부분을 경험치바의 왼쪽에 두는 것은 어떨까요?

2023-05-29 12:14 UTC, r-u-sure approved these changes
이렇게 작성하는건 어떨까요?

2023-05-29 12:14 UTC, r-u-sure commented on check-and-talk/src/components/ProfileEdit.js
> +                        <div className='purple'></div>
render 메서드 안에서
`const colorList = ["red", "yellow", "green", "blue", "purple"];`
선언해주고
```suggestion
                        {colorList.map((v) => (<div className={v}></div>))}
````
이런식으로 코드를 짜면 관리하기 편할 것 같습니다

2023-05-29 12:14 UTC, r-u-sure approved these changes
이렇게 작성하는건 어떨까요?

2023-05-29 12:14 UTC, r-u-sure approved these changes
이렇게 작성하는건 어떨까요?

2023-05-30 00:44 UTC, 2jihye10 approved these changes
수고하셨습니다 🥹👍🏻

2023-05-30 00:45 UTC, merged